name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no /tmp/myimage.tar ${USER}@${HOST}:~
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            docker load < myimage.tar
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 8000:8000 \
              -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              -e MILVUS_HOST="${{ secrets.MILVUS_HOST }}" \
              -e MILVUS_PORT="${{ secrets.MILVUS_PORT }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -v ${HOME}/faiss_index:/code/faiss_index \
              user/app:latest
          '
